# Generated by Django 2.1.7 on 2020-08-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='code')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, verbose_name='rut')),
                ('dose', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='dose')),
                ('date', models.DateField(auto_now_add=True, verbose_name='date')),
                ('drug', models.CharField(max_length=255, verbose_name='drug')),
            ],
        ),
    ]
